name: My YourTomo cat
on:
  schedule:
    - cron: '23 */6 * * *'   # roda a cada 6 horas
  workflow_dispatch:         # permite rodar manualmente

permissions:
  contents: write

jobs:
  pet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prsdx/github-pet@v1
        with:
          username: alexheitorc
          timezone-offset-minutes: "-180"
          pet-name: "Mingau"   # opcional: dê o nome que quiser ao gato
